### ISSUE TITLE
List of street name for a city ?

### ISSUE THREAD

**Issue by armgilles** [DinoTools/python-overpy#22]
Hey, i try to list all street's name for a city.

For Bordeaux i try this : 

```
result = api.query("""
    area[name="Bordeaux"];way(area)[highway][name];out;
    """)
len(result.ways) #17332
```

This should be more more or less 2K streets.

Did i do something wrong ? :)

**Comment by Virtakuono** [comment]
If I am correct, your result should have multiple ways that correspond to the same street.
waynames = set([way.tags['name'] for way in result.ways]) narrows it down, not to two thousand, like you wanted. (where do you get this figure of 2K anyways?)
