### ISSUE TITLE
please include LICENSE, CHANGELOG.rst, docs, examples in the pypi tarball

### ISSUE THREAD

**Issue by sandrotosi** [DinoTools/python-overpy#41]
Hello!
I'm preparing overpy to be included in Debian, but i noticed that the tarball on pypi misses the LICENSE file: that is required to formally be included in Debian (and from a legal point of view to specify explicitly the license you are applying to your module) - could you include it in the next upload?

it would also be great if you can add a other files like CHANGELOG.rst, docs, examples which would allow me to include them in the packages distributed with Debian and improve the user experience.

thanks for considering,
Sandro

**Comment by phibos** [comment]
Hi Sandro,

sounds great. Why are you using the tarball from PyPi instead of the tarball from GitHub?

Regards PhiBo

**Comment by sandrotosi** [comment]
probably out of habits: we tend to prefer to use the pypi tarballs as they are what the developers release to their users (mainly via pip), so we'd rather take those releases as it's unusual to re-release the same version on pypi, while retagging/rereleasing in git is much more common (and will result in a package with the same version but different code) - this is the general idea and in now way implying you usually retag or so :)

**Comment by phibos** [comment]
All the files you requested should be in the next PyPi upload.

**Comment by sandrotosi** [comment]
thanks a ton, @phibos ! :)
