### ISSUE TITLE
Release 0.3.2 or 0.4.0-beta with latest bugfixes

### ISSUE THREAD

**Issue by grote** [DinoTools/python-overpy#45]
I am using this awesome library in one of my projects. Thanks a lot for it! :)

The last release was more than one and a half years ago. There have been many important fixes since then, but they haven't been released. Could you please make a release that includes some of the fixes?

I am personally interested in ac7df97ef4302d7eda46a6bb34a887e9b275748c to be included in a bugfix release.

**Comment by phibos** [comment]
I'm glad you like the library.

I will check all commits since 0.3.1 and all outstanding pull requests to release version 0.4 in a few days.

**Comment by grote** [comment]
Awesome, thanks a lot! :)

**Comment by phibos** [comment]
Version 0.4 has been released

**Comment by grote** [comment]
Great, thanks a lot! :)
