### ISSUE TITLE
OverpassTooManyRequests: Too many requests

### ISSUE THREAD

**Issue by rmarzocchi84** [DinoTools/python-overpy#56]
#### Python version Python 2.7.6

I run a script which perform some query starting from data that I read from a list file. 
After a few request I obtain the OverpassTooManyRequests: Too many requests error.

I partially solved this problem using a sleep time which I can increase... nevertheless sometime the sleep time is not enough and my script crash. 

How can avoid the crash and manage the well-known 429 error of the overpass API? 

Probably I can use the exception (exception overpy.exception.OverpassTooManyRequests) ? But I do not understand how?

**Comment by Teiron** [comment]
OverpassTooManyRequests may occur also when Overpass servers experience heavy load. The "gentle" way to avoid it would be to increase sleep time or write custom try-catch block which would re-try connection after some time.
You can also try changing the server you are querying (and on enterprise level spin your own overpass server).

**Comment by phibos** [comment]
I have added an FAQ entry about the TooManyRequests exception and I have started to implement a retry option. For more information have a look at the PR #59

**Comment by phibos** [comment]
I have merged the PR #59 into the master branch. OverPy should now be able to retry failed requests. You might also be interested in the [OverPy FAQ](https://python-overpy.readthedocs.io/en/latest/faq.html)
