### ISSUE TITLE
change BaseException to Exception?

### ISSUE THREAD

**Issue by wx0wk** [DinoTools/python-overpy#70]
##### Issue type
 - Bug Report

##### OverPy version
```
0.4
```

##### OS
 - Ubuntu 16.04

#### Python version
 - Python 3.5

##### Summary

When using celery task with overpy, a `try`-`catch Exception` block will not catch OverPyException, which is inherited from `BaseException`, and it will make Celery main process exit. 

It's recommended to use `Exception`s instead of `BaseException` in [Python's doc](https://docs.python.org/3/library/exceptions.html#bltin-exceptions)

##### Steps to reproduce

```
from celery import shared_task
import logging
import overpy

logger = logging.getLogger()

@shared_task
def task(coords):
    api = overpy.Overpass(url='some_inavlid_url')
    try:
        result = api.query('way(around:40,{},{})["maxspeed"];out;'.format(coords[1], coords[0]))
    except Exception as e:
        logger.exception(e)
        # other exception handling code
    else:
        pass # other processing code
    return result
```
##### Expected results

Whenever the query fail (time out or whatever), it raise an `Exception` and been catch by `except` so I can deal with it and end this task normally.

##### Actual results

Raise `BaseException`, cause Celery MainProcess exit, log showing 
`[ERROR:MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 0.',)`

**Comment by phibos** [comment]
Thank you for reporting the issue and providing a patch.
