### ISSUE TITLE
Is there a possibility to query a local Overpass db?

### ISSUE THREAD

**Issue by Erhanjinn** [DinoTools/python-overpy#73]
Hi,

is there a possibility to query a local .osm copy of data? Can I make the Overpass API to switch to local db?

Thanks!

**Comment by phibos** [comment]
You can use the ```url``` parameter of the ```Overpass``` class.

```
api = overpy.Overpass(url='http://my-local-overpass.localhost/api/interpreter')
```

**Comment by phibos** [comment]
Seems like the question has been answered. Issue closed.
