### ISSUE TITLE
Updating pip package

### ISSUE THREAD

**Issue by fingoldo** [DinoTools/python-overpy#81]
Hello, thank you for your work!
Can you update pip package please? Currently it is lacking max_retry_count parameter, contrary to the docs...

**Comment by tpikonen** [comment]
Seconded. It would be really nice to get a new release (tag) to get the downstream distributions to update their packages.

**Comment by phibos** [comment]
There are still some open tickets for the 0.5 but I will have a look if we could move them to the next release and make a 0.5 release in the next few days.

**Comment by phibos** [comment]
I have published version 0.5. I have to review the changes for version 0.6 and drop support for python 2.x
