### ISSUE TITLE
.value() missed

### ISSUE THREAD

**Issue by okaka1221** [DinoTools/python-overpy#85]
https://github.com/DinoTools/python-overpy/blob/8aa4bafc8e9b336d4f8da7c993ca545494a0e5a9/overpy/__init__.py#L285

`for element in other_collection_map[element_type]:` 
should be
`for element in other_collection_map[element_type].values():`

**Comment by phibos** [comment]
I had a look at your suggestion, but I think it is not correct the values in the dict ```other_collection_map``` are lists and lists don't have an attribute called ```values()```.

Why do you think ```values()``` should work. Maybe there is some other error?

**Comment by phibos** [comment]
No feedback and  no issues with current implementation found. Closing.
