### ISSUE TITLE
Using lists is too slow

### ISSUE THREAD

**Issue by dyoxyne** [DinoTools/python-overpy#9]
Hello,

Thanks for the package.
I used it and found that it was really slow to use the property nodes of a way element.
This is basically due to the use of a list for result.nodes.

The time complexity of way.nodes is: O(number_of_nodeId * number_of_nodes).
It can be done in: O(number_of_nodeId) by using a dictionary.

It can also be generalized for relations and ways.

**Comment by DemarsM** [comment]
+1

**Comment by phibos** [comment]
Please have a look at the use_dict branch. The code has been merged from @dbuse and it passes all tests.
